Develop
CarlosIVI/AIK-Portal pull request #1
Opened 2020-10-24 16:28 UTC by sjnarvaez17

2020-10-24 17:49 UTC, juanfe2793 requested changes

2020-10-24 17:49 UTC, juanfe2793 commented on Infrastructure/infrastructure_template/cloud/main.tf
> +  min_size             = 2
Puede ser 1 para probrar

2020-10-24 17:49 UTC, juanfe2793 commented on Infrastructure/infrastructure_template/cloud/main.tf
> +  user_data       = <<EOF
En el user data pueden usar:
`user_data = file("../scripts/nvm.sh")`
En el nuevo directorio ponen el script que van a ejecutar. Lo ideal es hacer todo con salt.

2020-10-24 17:49 UTC, juanfe2793 commented on configuration_management/states/yum-s3/files/s3.repo
> +baseurl=https://s3.amazonaws.com/artifacts-automatizacion
No vi la creación de este bucket en el TF main.tf

2020-10-31 21:33 UTC, CarlosIVI commented on Infrastructure/infrastructure_template/cloud/main.tf
> +  min_size             = 2
Done!

2020-10-31 21:40 UTC, CarlosIVI commented on Infrastructure/infrastructure_template/cloud/main.tf
> +  user_data       = <<EOF
Ese script es la primera aproximación de Salt, ¿Recomiendas dejarlo para la entrega final o mejor configurarlo en el LaunchConfig?

2020-11-05 17:56 UTC, juanfe2793 requested changes

2020-11-05 17:56 UTC, juanfe2793 commented on Infrastructure/infrastructure_template/cloud/main.tf
> +  min_size             = 2
Sigo viendo 2

2020-11-07 21:50 UTC, CarlosIVI commented on Infrastructure/infrastructure_template/cloud/main.tf
> +  min_size             = 2
Done x2

2020-11-07 22:25 UTC, sjnarvaez17 commented on configuration_management/states/yum-s3/files/s3.repo
> +baseurl=https://s3.amazonaws.com/artifacts-automatizacion
ya se creó

2020-11-11 20:44 UTC, juanfe2793 approved these changes

2020-11-11 20:44 UTC, juanfe2793 commented on Infrastructure/infrastructure_template/cloud/main.tf
> +    depends_on                = [aws_subnet.aik-subnet-public2-est10]
epaaa cómo van a poner una DB pública. En este caso les va a funcionar pero es un riesgo gigante. Re mala práctica. 

Es cómo dejar el banco sin alarmas, sistema de seguridad.

2020-11-11 20:46 UTC, merged